main: com.massivecraft.factions.Factions
name: Factions
version: 2.12.1
website: https://www.massivecraft.com/factions
description: §eFactions allows the players to team up and claim land as their own and start wars with other factions. This way we hope to inspire politics, intrigue, and team spirit. §aCayorion§e from §aMassiveCraft§e is the developer. Feel free to visit us at §bhttps://www.massivecraft.com
authors: [OnePound, Cayorion, Madus, Ulumulu1510, MarkehMe, Brettflan]
depend: [MassiveCore]
softdepend: [PermissionsEx, Permissions, Essentials, EssentialsChat, HeroChat, iChat, LocalAreaChat, LWC, nChat, ChatManager, AuthMe, Vault, Spout, WorldEdit, WorldGuard, AuthDB, CaptureThePoints, CombatTag]
commands:
  tpa:
    description: sends another player a teleport request!
    usage: /tpa <name>
  tpyes:
    description: accepts another players teleport request!
    usage: /tpyes <name>
  tpaccept:
    description: accepts another players teleport request!
    usage: /tpaccept <name>
  sethome:
    description: set a home
    usage: /sethome <name>
  delhome:
    description: delete a home
    usage: /delhome <name>
  home:
    description: teleport to a home
    usage: /home <name>
  tpahere:
    description: teleport a player to you
    usage: /tpahere <name>
  back:
    description: teleport to your previous location
    usage: /back
  skills:
    description: open skills inventory
    usage: /skills
  setspawn:
    description: sets the spawn location
    usage: /setspawn
  spawn:
    description: teleports you to spawn
    usage: /spawn
  setwarp:
    description: set a warp
    usage: /setwarp
  warp:
    description: teleport to a warp
    usage: /warp
  delwarp:
    description: delete a warp
    usage: /delwarp
  vanish:
    description: vanish
    usage: /vanish
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  factions.access: {description: manage access, with the proper fperm, default: false}
  factions.access.faction: {description: grant faction access, with the proper fperm, default: false}
  factions.access.player: {description: grant player access, with the proper fperm, default: false}
  factions.access.view: {description: view access, default: false}
  factions.override: {description: enable override mode, default: false}
  factions.basecommand: {description: use factions base command, default: false}
  factions.claim: {description: claim faction territory, default: false}
  factions.claim.one: {description: claim a single chunk, default: false}
  factions.claim.auto: {description: claim as you walk around, default: false}
  factions.claim.fill: {description: claim by filling, default: false}
  factions.claim.square: {description: claim by square and radius, default: false}
  factions.claim.circle: {description: claim by circle and radius, default: false}
  factions.claim.all: {description: claim all faction land, default: false}
  factions.claim.line: {description: claim in a line, default: false}
  factions.create: {description: create new faction, default: false}
  factions.description: {description: change faction description, default: false}
  factions.disband: {description: disband faction, default: false}
  factions.expansions: {description: list expansions, default: false}
  factions.faction: {description: show faction information, default: false}
  factions.flag: {description: manage faction flags, default: false}
  factions.flag.list: {description: list flags, default: false}
  factions.flag.set: {description: set flags, default: false}
  factions.flag.show: {description: show flags, default: false}
  factions.home: {description: teleport to faction home, default: false}
  factions.invite: {description: manage invites, default: false}
  factions.invite.list: {description: list invited players, default: false}
  factions.invite.list.other: {description: list invited players of another factions, default: false}
  factions.invite.add: {description: invite player, default: false}
  factions.invite.remove: {description: revoke an invite, default: false}
  factions.join: {description: join faction, default: false}
  factions.join.others: {description: have another player join faction, default: false}
  factions.kick: {description: kick player from faction, default: false}
  factions.leave: {description: leave your faction, default: false}
  factions.list: {description: list all factions, default: false}
  factions.map: {description: show territory map, default: false}
  factions.money: {description: manage faction money, default: false}
  factions.money.balance: {description: show faction money, default: false}
  factions.money.balance.any: {description: show another factions money, default: false}
  factions.money.deposit: {description: deposit to faction, default: false}
  factions.money.f2f: {description: transfer f --> f, default: false}
  factions.money.f2p: {description: transfer f --> p, default: false}
  factions.money.p2f: {description: transfer p --> f, default: false}
  factions.money.withdraw: {description: withdraw from faction, default: false}
  factions.motd: {description: faction motd, default: false}
  factions.open: {description: set if invitation is required to join, default: false}
  factions.perm: {description: change faction permissions, default: false}
  factions.perm.list: {description: list perms, default: false}
  factions.perm.set: {description: set perms, default: false}
  factions.perm.show: {description: show perms, default: false}
  factions.player: {description: show player information}
  factions.powerboost: {description: manage powerboost, default: false}
  factions.powerboost.faction: {description: show faction powerboost, default: false}
  factions.powerboost.player: {description: show player powerboost, default: false}
  factions.powerboost.set: {description: set powerboost, default: false}
  factions.rank: {description: manage/show ranks, default: false}
  factions.rank.show: {description: show rank, default: false}
  factions.rank.action: {description: change rank, default: false}
  factions.relation: {description: manage faction relations, default: false}
  factions.relation.list: {description: list all factions with certain relation, default: false}
  factions.relation.set: {description: set relation wish to another faction, default: false}
  factions.relation.wishes: {description: list the relation wishes, default: false}
  factions.seechunk: {description: see the chunk you stand in, default: false}
  factions.seechunkold: {description: see the chunk you stand in, default: false}
  factions.sethome: {description: set the faction home, default: false}
  factions.setpower: {description: set power, default: false}
  factions.status: {description: show status, default: false}
  factions.name: {description: set faction name, default: false}
  factions.title: {description: set player title, default: false}
  factions.title.color: {description: set player title with color, default: false}
  factions.territorytitles: {description: toggle territory titles, default: false}
  factions.unclaim: {description: unclaim faction territory, default: false}
  factions.unclaim.one: {description: unclaim a single chunk, default: false}
  factions.unclaim.auto: {description: unclaim as you walk around, default: false}
  factions.unclaim.fill: {description: unclaim by filling, default: false}
  factions.unclaim.square: {description: unclaim by square and radius, default: false}
  factions.unclaim.circle: {description: unclaim by circle and radius, default: false}
  factions.unclaim.all: {description: unclaim all faction land, default: false}
  factions.unsethome: {description: unset faction home, default: false}
  factions.unstuck: {description: teleport to nearest wilderness, default: false}
  factions.config: {description: edit the factions config, default: false}
  factions.clean: {description: clean the factions database, default: false}
  factions.version: {description: see plugin version, default: false}
  factions.find: {description: find recruiting factions, default: true}
  factions.stealth: {description: stop effecting other\'s flight, default: true}
  factions.recruiting: {description: set faction recruitment status, default: true}
  factions.url: {description: set faction url, default: true}
  factions.upgrade: {description: upgrade your faction, default: true}
  factions.wild: {description: teleport to a random location, default: true}
  factions.warp: {description: go to a faction warp, default: true}
  factions.listwarps: {description: list your faction warps, default: true}
  factions.setwarp: {description: set a faction warp, default: true}
  factions.deletewarp: {description: delete a faction warp, default: true}
  factions.top: {description: list the top factions, default: true}
  factions.addVictoryPoints: {description: give victory points, default: false}
  factions.takeVictoryPoints: {description: take victory points, default: false}
  factions.class: {description: show your class information, default: true}
  factions.setClass: {description: set your class, default: false}
  factions.url: {description: set faction url, default: true}
  factions.wealth: {description: list factions by wealth, default: true}
  factions.capital: {description: set a faction capital, default: true}
  factions.tnt: {description: virtual tnt storage, default: true}
  factions.tnt.amount: {description: gets how much tnt your faction has stored, default: true}
  factions.tnt.add: {description: moves your tnt to your factions tnt storage, default: true}
  factions.tnt.take: {description: take from your factions tnt storage, default: true}
  factions.tnt.fill: {description: fill dispensers with tnt from storage, default: true}
  factions.boost.view: {description: view your mcmmo boosts, default: true}
  factions.boost.setplayer: {description: set your personal mcmmo boosts, default: true}
  factions.boost.setfaction: {description: set your faction mcmmo boosts, default: true}
  factions.playerleaderboardset: {description: set leaderboard locations, default: false}
  
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  factions.*:
    children:
      factions.access: true
      factions.access.faction: true
      factions.access.player: true
      factions.access.view: true
      factions.override: true
      factions.basecommand: true
      factions.claim: true
      factions.claim.one: true
      factions.claim.auto: true
      factions.claim.fill: true
      factions.claim.square: true
      factions.claim.circle: true
      factions.claim.all: true
      factions.claim.line: true
      factions.create: true
      factions.demote: true
      factions.description: true
      factions.disband: true
      factions.expansions: true
      factions.faction: true
      factions.flag: true
      factions.flag.list: true
      factions.flag.set: true
      factions.flag.show: true
      factions.home: true
      factions.invite: true
      factions.invite.list: true
      factions.invite.list.other: true
      factions.invite.add: true
      factions.invite.remove: true
      factions.join: true
      factions.join.others: true
      factions.kick: true
      factions.leader: true
      factions.leader.any: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.money: true
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
      factions.money.withdraw: true
      factions.motd: true
      factions.officer: true
      factions.officer.any: true
      factions.open: true
      factions.perm: true
      factions.perm.list: true
      factions.perm.set: true
      factions.perm.show: true
      factions.player: true
      factions.powerboost: true
      factions.powerboost.faction: true
      factions.powerboost.player: true
      factions.powerboost.set: true
      factions.promote: true
      factions.relation: true
      factions.relation.list: true
      factions.relation.set: true
      factions.relation.wishes: true
      factions.seechunk: true
      factions.seechunkold: true
      factions.sethome: true
      factions.setpower: true
      factions.status: true
      factions.name: true
      factions.title: true
      factions.title.color: true
      factions.territorytitles: true
      factions.unclaim: true
      factions.unclaim.one: true
      factions.unclaim.auto: true
      factions.unclaim.fill: true
      factions.unclaim.square: true
      factions.unclaim.circle: true
      factions.unclaim.all: true
      factions.unsethome: true
      factions.unstuck: true
      factions.config: true
      factions.clean: true
      factions.version: true
      factions.tnt.amount: true
      factions.tnt.add: true
      factions.tnt.take: true
      factions.tnt.fill: true
      factions.boost.view: true
      factions.boost.setfaction: true
      factions.boost.setplayer: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  factions.kit.op:
    default: op
    children:
      factions.*: true
  factions.kit.rank3:
    default: false
    children:
      factions.kit.rank2: true
      factions.config: true
      factions.clean: true
  factions.kit.rank2:
    default: false
    children:
      factions.kit.rank1: true
      factions.powerboost.set: true
      factions.join.others: true
      factions.leader.any: true
      factions.officer.any: true
      factions.access.any: true
      factions.setpower: true
  factions.kit.rank1:
    default: false
    children:
      factions.kit.rank0: true
      factions.override: true
      factions.invite.list.other: true
  factions.kit.rank0:
    default: false
    children:
      factions.access: true
      factions.access.faction: true
      factions.access.player: true
      factions.access.view: true
      factions.basecommand: true
      factions.claim: true
      factions.claim.one: true
      factions.claim.auto: true
      factions.claim.fill: true
      factions.claim.square: true
      factions.claim.circle: true
      factions.claim.all: true
      factions.create: true
      factions.demote: true
      factions.description: true
      factions.disband: true
      factions.expansions: true
      factions.faction: true
      factions.flag: true
      factions.flag.list: true
      factions.flag.set: true
      factions.flag.show: true
      factions.home: true
      factions.invite: true
      factions.invite.list: true
      factions.invite.add: true
      factions.invite.remove: true
      factions.join: true
      factions.kick: true
      factions.leader: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.money: true
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
      factions.money.withdraw: true
      factions.motd: true
      factions.officer: true
      factions.open: true
      factions.perm: true
      factions.perm.list: true
      factions.perm.set: true
      factions.perm.show: true
      factions.player: true
      factions.promote: true
      factions.powerboost: true
      factions.powerboost.faction: true
      factions.powerboost.player: true
      factions.rank: true
      factions.rank.show: true
      factions.rank.action: true
      factions.relation: true
      factions.relation.list: true
      factions.relation.set: true
      factions.relation.wishes: true
      factions.seechunk: true
      factions.seechunkold: true
      factions.sethome: true
      factions.status: true
      factions.name: true
      factions.title: true
      factions.title.color: true
      factions.territorytitles: true
      factions.unclaim: true
      factions.unclaim.one: true
      factions.unclaim.auto: true
      factions.unclaim.fill: true
      factions.unclaim.square: true
      factions.unclaim.circle: true
      factions.unclaim.all: true
      factions.unsethome: true
      factions.unstuck: true
      factions.version: true
  factions.kit.default:
    default: true
    children:
      factions.kit.rank0: true
